version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # uvicorn
      - "8081:8081"  # HTTP
      - "8765:8765"  # WebSocket
      - "9989:9989"  # TCP
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/products_db

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local